[package]
name = "rust"
version = "0.1.0"
repository = "https://github.com/alexcrichton/splay-rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
